CLEARML:
  PREPROCESS:
    PROJECT_NAME: "Stackoverflow/Preprocess"
    PIPELINE_NAME: "Preprocessing pipeline"
    TASK_ACQUISITION: "Files acquisition"
    TASK_MERGE: "Files merging"
  EXPERIMENTS:
    PROJECT_NAME: "Stackoverflow/Experiments"
    TASK_QUEST_EXPLORATION: "Questions exploration analysis"
    TASK_PROGRAMING_LANG: "Programming languages analysis"

FILE_REPO:
  ANSWERS: ["13ozwix5ZJ6XzqAWDTZ6qHHqrDAH6RHtW", "12ImbkAvOvlxKXcPgEOMnSoqsYAnJGKEr", "1mRGm5EvNaWOpi54SzbieaDU8PZsx9fzA"]
  QUESTIONS: ["1-RRUt5v2CskovT_GkPDa0U9lHjecvrIw","1FVMu4my90PKesOhH-o_gnHDB_P93dO7m", "19ZSqSppUDjQXoq8TLraCHavabbuFUzHe"]
  TAGS: ["1C75CrYksuiS61tSnThqb5tM1fVENpBXv", "1TnTUVDJ0XbZ70xTBwoJjte5T-M3oH9Wo", "1bNO8RJEGrn07JiNDSpLE8Wkc03ZSRE5I"]

DATASETS:
  QUEST_NAME: "QUESTIONS_merged"
  TAGS_NAME: "TAGS_merged"
  ANSW_NAME: "ANSWERS_merged"

GIT:
  GITLAB_URL: "https://github.com/michelecec/stackoverflow.git"
  GITLAB_BRANCH: "main"

GENERAL:
  MAX_ROW_SIZE: 100000